[package]
name = "milti-threaded_search"
version = "0.1.0"
authors = ["13r0ck <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3"
lipsum = "0.8.0"
